---
name: Publish to Exchange & Deploy to CH2.0
on:
  push:
    branches:
      - master
jobs:
  build_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Publish to Exchange
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}      
        run: |
          mvn deploy -e --settings .maven/settings.xml -DskipMunitTests \
          -Dusername="$USERNAME" \
          -Dpassword="$PASSWORD"
  deploy:
    runs-on: ubuntu-latest
    needs: build_publish
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17    
      - name: Deploy to CloudHub 2.0
        run: >
          mvn deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy -Dusername="${{secrets.USERNAME }}" -Dpassword="${{ secrets.PASSWORD }}"
